# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.x'
    includePreviewVersions: true

- script: dotnet build
  displayName: 'build'

- script: dotnet test --no-build --output detailed 
  displayName: 'new dotnet test with colors'
